
icon: /images/avatar.jpg
avatar: /images/avatar.jpg
background: /images/background_s.jpg


loading: 
  enable: true 
  loading_gif: /images/loading.gif


color_scheme: blue # red, blue, green, orange, purple, pink, gray
color_slider: true

tags_colors:
    - "#ffa2c4"
    - "#00bcd4"
    - "#03a9f4"
    - "#00a596"
    - "#ff7d73"

highlight:
  enable: true
  style: github-dark # See available styles at
  max_height: 500 # px

search:
  enable: true
  position: right # left, top, right
  placeholder: "Search..."

menu: # icon class reference: https://fontawesome.com/icons
  enable: true # not suggest to disable it :)
  position: top # left, top, right
  align: center # start, center, end
  auto_hide: true # not work when menu at left or right
  items:
    Home:
      link: /
      icon: fa-solid fa-house
    About:
      link: /about/
      icon: fa-solid fa-user
    Archives:
      link: /archives/
      icon: fa-solid fa-archive
    Categories: 
      link: /categories/
      icon: fa-solid fa-folder
    Tags:
      link: /tags/
      icon: fa-solid fa-tags
    Links:
      link: /links/
      icon: fa-solid fa-link

post:
  show_date: true
  show_category: true
  show_tags: true
  read_more:
    enable: true
    text: "READ MORE"
    position: right # left, bottom, right

cards:
  enable: true
  position: right # left, right
  description: | 
    Welcome to my blog!
  iconlinks:
    github:
      link: https://github.com/
      icon: fa-brands fa-github
    twitter:
      link: https://twitter.com/
      icon: fa-brands fa-twitter
    facebook:
      link: https://facebook.com/
      icon: fa-brands fa-facebook
  links:
    Home: /
    About: /about/
    Archives: /archives/
    Categories: /categories/
    Tags: /tags/
    Links: /links/
  canlendars: true

comments:
  enable: false
  Giscus:
    enable: false
    repo: 
    repo_id: 
    category: 
    category_id:
  Gitalk:
    enable: false
    site_id:

footer:
  enable: true
  since: 2025
  # Customize the server domain name ICP
  ICP:
      enable: false
      code:
      link: